-- MySQL Script generated by MySQL Workbench
-- Thu Apr  9 18:46:38 2015
-- Model: New Model    Version: 1.0
SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema bima
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `bima` DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci ;
USE `bima` ;

-- -----------------------------------------------------
-- Table `bima`.`users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bima`.`users` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NULL,
  `age` VARCHAR(45) NULL,
  `national_id` VARCHAR(45) NULL,
  `phone` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bima`.`messages`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bima`.`messages` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `phone` VARCHAR(45) NULL,
  `message` VARCHAR(45) NULL,
  `time_sent` TIMESTAMP NULL,
  `type` INT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bima`.`payments`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bima`.`payments` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `user_id` VARCHAR(45) NULL,
  `amount` VARCHAR(45) NULL,
  `payment_type` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bima`.`insurance`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bima`.`insurance` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `status` INT NULL,
  `expiry` DATETIME NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
